[package]
authors = ["Sebastien Rousseau"]
categories = ["development-tools"]
description = "Highly Performant Utility And Wrapper Functions Library For Rust"
edition = "2021"
homepage = "https://minifunctions.com"
include = [
    "/Cargo.toml",
    "/LICENSE-Apache",
    "/LICENSE-MIT",
    "/README.md",
    "/src/**",
    "/tests/**",
]
keywords = ["functions"]
license = "Apache-2.0 OR MIT"
name = "mini-functions"
readme = "README.md"
repository = "https://github.com/sebastienrousseau/mini-functions.git"
rust-version = "1.57.0"
version = "0.0.1"

[badges]
maintenance = { status = "actively-developed" }

[lib]
bench = false

[[test]]
name = "tests"
path = "./tests/main.rs"

[dependencies]
time = { version ="0.3.17", features = ["default"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
debug = false # Disable debug information
incremental = false # Disable incremental compilation
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
panic = "abort" # Strip expensive panic clean-up logic
strip = "symbols"  # Automatically strip symbols from the binary.
