[build]
target = "x86_64-unknown-linux-gnu"

[targets.x86_64-unknown-linux-gnu]
image = "rust:latest"
compiler = "gcc"

[targets.x86_64-unknown-linux-musl]
image = "rust:latest"
compiler = "musl-gcc"

[targets.x86_64-apple-darwin]
image = "rust:latest"
compiler = "clang"

[targets.aarch64-apple-darwin]
image = "rust:latest"
compiler = "clang"

[targets.x86_64-pc-windows-msvc]
image = "rust:latest"
compiler = "cl.exe"
