[build]
target = "x86_64-unknown-linux-gnu"

[targets.x86_64-unknown-linux-gnu]
image = "rust:latest"

[targets.x86_64-apple-darwin]
image = "rust:1.57.0"

[targets.x86_64-pc-windows-msvc]
image = "rust:1.57.0"
