[build]
target = "x86_64-unknown-linux-gnu"

[targets.x86_64-unknown-linux-gnu]
image = "rust:latest"
compiler = "gcc"

[targets.x86_64-pc-windows-gnu]
image = "rust:latest"
compiler = "mingw"

[targets.x86_64-apple-darwin]
image = "rust:latest"
compiler = "clang"
