name: ❯ release

on: [push, pull_request]

env:
  PACKAGE_NAME: mini-functions
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      # - name: Test
      #   run: cargo test --release
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Upload Application
        run: |
          mv ./target/release/osx/${PACKAGE_NAME}.dmg ./${PACKAGE_NAME}-${GITHUB_REF##*/}.dmg $GITHUB_TOKEN
