on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry 🧑‍💼
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build 🚀
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Toolchain 🛠
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Extract version number 📜
        run: |
          version=$(grep version Cargo.toml | cut -d '"' -f 2)
          echo "version=$version"

      - name: Build with cross 🏗
        run: |
          # Build the binary
          cargo install cross
          cargo clean
          cross build --release --target=${{ matrix.target }}

      - name: Check if binary exists 📂
        run: ls -la target/${{ matrix.target }}/release/mini-functions

      - name: Rename binary 📂
        run: |
          mv target/${{ matrix.target }}/release/mini-functions target/${{ matrix.target }}/release/mini-functions-$version-${{ github.sha }}

      - name: Check if renamed binary exists 📂
        run: ls -la target/${{ matrix.target }}/release/mini-functions-$version-${{ github.sha }}

      - name: Generate Changelog 📜
        run: |
          # Generate a changelog based on the commit history
          git log --oneline --decorate --color > changelog.txt

          # Add a header to the changelog
          echo "# Changelog" > ${{ github.workspace }}-CHANGELOG.txt
          echo >> ${{ github.workspace }}-CHANGELOG.txt

          # Append the commit history to the changelog
          cat changelog.txt >> ${{ github.workspace }}-CHANGELOG.txt

      - name: Create binaries folder 📂
        run: mkdir -p binaries

      - name: Copy binary 📂
        run: |
          cp target/${{ matrix.target }}/release/mini-functions-$version-${{ github.sha }} binaries/mini-functions.${{ matrix.target }}

      - name: Release 🚀
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            binaries/mini-functions.${{ matrix.target }}
          name: ${{ github.workspace }}
          tag_name: ${{ github.workspace }}
          draft: false
          prerelease: false
