name: ❯ release

on: [push, pull_request]

env:
  PACKAGE_NAME: mini-functions
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    name: Create and Publish Release
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Please see the root of the repository for the CHANGELOG.md
          draft: true
          prerelease: false

      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_TOKEN }}

      - name: Create Binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
