name: ❯ rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-windows-gnu
          - aarch64-apple-darwin

        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-windows-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install rustfmt 🦀
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          profile: minimal
          toolchain: stable

      - name: Run rustfmt 🦀
        run: rustup component add rustfmt

      - name: Check formatting 🦀
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --verbose

      - name: Build 🚀
        run: cargo build --release --target $TARGET --out-dir target/release

      - name: Run tests 🧪
        run: cargo test --release --target $TARGET --out-dir target/release

      - name: Upload artifacts 📦
        uses: actions/upload-artifact@v2
        with:
          name: mini-functions
          path: target/release
