name: ❯ weekly

env:
  CARGO_TERM_COLOR: always

on:
  schedule:
    - cron: 00 3 * * 1
jobs:
  build:
    strategy:
      matrix:
        rust: [stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.rust }}
      - run: rustup default ${{ matrix.rust }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo update
      - run: cargo build --all-features
      - run: cargo test --all-features
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets -- --deny warnings
